title: "MiniGo 收納誌"
description: "分享簡約生活、整理術與收納技巧"
url: "https://minigogoo.com"
baseurl: ""   # 你使用 apex domain → 必須為空

author:
  name: "MiniGo"

markdown: kramdown
highlighter: rouge

permalink: /:categories/:title/

remote_theme: StartBootstrap/startbootstrap-clean-blog-jekyll

paginate: 5
paginate_path: "/page:num/"
plugins:
  - jekyll-paginate
  - jekyll-remote-theme

header:
  background: "/assets/img/home-bg.jpg"

sass:
  style: compressed

social:
  email: ""
  instagram: ""
  github: "https://github.com/wks9722"
  facebook: ""

exclude:
  - "node_modules"
  - "package.json"
  - "gulpfile.js"
  - "package-lock.json"
